M48
; DRILL file {KiCad 8.0.6+1} date 2025-02-24T18:19:53+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-24T18:19:53+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.580
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.660
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.700
%
G90
G05
T2
X34.835Y-64.0
T3
X35.0Y-30.0
X35.0Y-72.0
X112.0Y-30.0
X112.0Y-72.0
T1
X34.835Y-56.71G85X34.835Y-56.29
G05
M30
